//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc3LetsShopProject.MendixOrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.com/", ConfigurationName="MendixOrderService.OrderManagementPortType")]
    public interface OrderManagementPortType {
        
        // CODEGEN: Generating message contract since the operation GetOrderVoorGebuiker is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderVoorGebuiker", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponse GetOrderVoorGebuiker(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderVoorGebuiker", ReplyAction="*")]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponse> GetOrderVoorGebuikerAsync(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest request);
        
        // CODEGEN: Generating message contract since the operation GetOrderRegels is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderRegels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponse GetOrderRegels(Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderRegels", ReplyAction="*")]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponse> GetOrderRegelsAsync(Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest request);
        
        // CODEGEN: Generating message contract since the operation AddOrderForGebruiker is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/AddOrderForGebruiker", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse1 AddOrderForGebruiker(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/AddOrderForGebruiker", ReplyAction="*")]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse1> AddOrderForGebruikerAsync(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest request);
        
        // CODEGEN: Generating message contract since the operation AddOrderRegelToOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/AddOrderRegelToOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponse AddOrderRegelToOrder(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/AddOrderRegelToOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponse> AddOrderRegelToOrderAsync(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderVoorGebuiker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long gebruikerIdField;
        
        private GetOrderVoorGebuikerOrderStatus orderStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GetOrderVoorGebuikerOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum GetOrderVoorGebuikerOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderVoorGebuikerResponseOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderNummerField;
        
        private System.DateTime orderDatumField;
        
        private GetOrderVoorGebuikerResponseOrderOrderStatus orderStatusField;
        
        private long gebruikerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OrderNummer {
            get {
                return this.orderNummerField;
            }
            set {
                this.orderNummerField = value;
                this.RaisePropertyChanged("OrderNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime OrderDatum {
            get {
                return this.orderDatumField;
            }
            set {
                this.orderDatumField = value;
                this.RaisePropertyChanged("OrderDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public GetOrderVoorGebuikerResponseOrderOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum GetOrderVoorGebuikerResponseOrderOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderVoorGebuikerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker;
        
        public GetOrderVoorGebuikerRequest() {
        }
        
        public GetOrderVoorGebuikerRequest(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker) {
            this.GetOrderVoorGebuiker = GetOrderVoorGebuiker;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderVoorGebuikerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderVoorGebuikerResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Order", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponseOrder[] GetOrderVoorGebuikerResponse1;
        
        public GetOrderVoorGebuikerResponse() {
        }
        
        public GetOrderVoorGebuikerResponse(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponseOrder[] GetOrderVoorGebuikerResponse1) {
            this.GetOrderVoorGebuikerResponse1 = GetOrderVoorGebuikerResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderRegels : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderNummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OrderNummer {
            get {
                return this.orderNummerField;
            }
            set {
                this.orderNummerField = value;
                this.RaisePropertyChanged("OrderNummer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderRegelsResponseOrderRegel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelIdField;
        
        private long leverancierIdField;
        
        private decimal verkoopprijsField;
        
        private long aantalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ArtikelId {
            get {
                return this.artikelIdField;
            }
            set {
                this.artikelIdField = value;
                this.RaisePropertyChanged("ArtikelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LeverancierId {
            get {
                return this.leverancierIdField;
            }
            set {
                this.leverancierIdField = value;
                this.RaisePropertyChanged("LeverancierId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long Aantal {
            get {
                return this.aantalField;
            }
            set {
                this.aantalField = value;
                this.RaisePropertyChanged("Aantal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderRegelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public Mvc3LetsShopProject.MendixOrderService.GetOrderRegels GetOrderRegels;
        
        public GetOrderRegelsRequest() {
        }
        
        public GetOrderRegelsRequest(Mvc3LetsShopProject.MendixOrderService.GetOrderRegels GetOrderRegels) {
            this.GetOrderRegels = GetOrderRegels;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderRegelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderRegelsResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderRegel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponseOrderRegel[] GetOrderRegelsResponse1;
        
        public GetOrderRegelsResponse() {
        }
        
        public GetOrderRegelsResponse(Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponseOrderRegel[] GetOrderRegelsResponse1) {
            this.GetOrderRegelsResponse1 = GetOrderRegelsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderForGebruiker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddOrderForGebruikerOrder orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AddOrderForGebruikerOrder Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderForGebruikerOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime orderDatumField;
        
        private AddOrderForGebruikerOrderOrderStatus orderStatusField;
        
        private long gebruikerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime OrderDatum {
            get {
                return this.orderDatumField;
            }
            set {
                this.orderDatumField = value;
                this.RaisePropertyChanged("OrderDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AddOrderForGebruikerOrderOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum AddOrderForGebruikerOrderOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderForGebruikerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddOrderForGebruikerResponseOrder orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AddOrderForGebruikerResponseOrder Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderForGebruikerResponseOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderNummerField;
        
        private System.DateTime orderDatumField;
        
        private AddOrderForGebruikerResponseOrderOrderStatus orderStatusField;
        
        private long gebruikerIdField;
        
        private AddOrderForGebruikerResponseOrderOrderRegel[] order_OrderRegelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OrderNummer {
            get {
                return this.orderNummerField;
            }
            set {
                this.orderNummerField = value;
                this.RaisePropertyChanged("OrderNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime OrderDatum {
            get {
                return this.orderDatumField;
            }
            set {
                this.orderDatumField = value;
                this.RaisePropertyChanged("OrderDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AddOrderForGebruikerResponseOrderOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderRegel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AddOrderForGebruikerResponseOrderOrderRegel[] Order_OrderRegel {
            get {
                return this.order_OrderRegelField;
            }
            set {
                this.order_OrderRegelField = value;
                this.RaisePropertyChanged("Order_OrderRegel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum AddOrderForGebruikerResponseOrderOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderForGebruikerResponseOrderOrderRegel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelIdField;
        
        private System.Nullable<long> leverancierIdField;
        
        private System.Nullable<decimal> verkoopprijsField;
        
        private System.Nullable<long> aantalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ArtikelId {
            get {
                return this.artikelIdField;
            }
            set {
                this.artikelIdField = value;
                this.RaisePropertyChanged("ArtikelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<long> LeverancierId {
            get {
                return this.leverancierIdField;
            }
            set {
                this.leverancierIdField = value;
                this.RaisePropertyChanged("LeverancierId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<decimal> Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<long> Aantal {
            get {
                return this.aantalField;
            }
            set {
                this.aantalField = value;
                this.RaisePropertyChanged("Aantal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderForGebruikerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruiker AddOrderForGebruiker;
        
        public AddOrderForGebruikerRequest() {
        }
        
        public AddOrderForGebruikerRequest(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruiker AddOrderForGebruiker) {
            this.AddOrderForGebruiker = AddOrderForGebruiker;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderForGebruikerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse AddOrderForGebruikerResponse;
        
        public AddOrderForGebruikerResponse1() {
        }
        
        public AddOrderForGebruikerResponse1(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse AddOrderForGebruikerResponse) {
            this.AddOrderForGebruikerResponse = AddOrderForGebruikerResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderRegelToOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddOrderRegelToOrderOrderRegel orderRegelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AddOrderRegelToOrderOrderRegel OrderRegel {
            get {
                return this.orderRegelField;
            }
            set {
                this.orderRegelField = value;
                this.RaisePropertyChanged("OrderRegel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderRegelToOrderOrderRegel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelIdField;
        
        private long leverancierIdField;
        
        private decimal verkoopprijsField;
        
        private long aantalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ArtikelId {
            get {
                return this.artikelIdField;
            }
            set {
                this.artikelIdField = value;
                this.RaisePropertyChanged("ArtikelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LeverancierId {
            get {
                return this.leverancierIdField;
            }
            set {
                this.leverancierIdField = value;
                this.RaisePropertyChanged("LeverancierId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long Aantal {
            get {
                return this.aantalField;
            }
            set {
                this.aantalField = value;
                this.RaisePropertyChanged("Aantal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderRegelToOrderResponseOrderRegel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelIdField;
        
        private long leverancierIdField;
        
        private decimal verkoopprijsField;
        
        private long aantalField;
        
        private AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegel order_OrderRegelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ArtikelId {
            get {
                return this.artikelIdField;
            }
            set {
                this.artikelIdField = value;
                this.RaisePropertyChanged("ArtikelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LeverancierId {
            get {
                return this.leverancierIdField;
            }
            set {
                this.leverancierIdField = value;
                this.RaisePropertyChanged("LeverancierId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long Aantal {
            get {
                return this.aantalField;
            }
            set {
                this.aantalField = value;
                this.RaisePropertyChanged("Aantal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegel Order_OrderRegel {
            get {
                return this.order_OrderRegelField;
            }
            set {
                this.order_OrderRegelField = value;
                this.RaisePropertyChanged("Order_OrderRegel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegelOrder orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegelOrder Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegelOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderNummerField;
        
        private System.DateTime orderDatumField;
        
        private AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegelOrderOrderStatus orderStatusField;
        
        private long gebruikerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OrderNummer {
            get {
                return this.orderNummerField;
            }
            set {
                this.orderNummerField = value;
                this.RaisePropertyChanged("OrderNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime OrderDatum {
            get {
                return this.orderDatumField;
            }
            set {
                this.orderDatumField = value;
                this.RaisePropertyChanged("OrderDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegelOrderOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum AddOrderRegelToOrderResponseOrderRegelOrder_OrderRegelOrderOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderRegelToOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrder AddOrderRegelToOrder;
        
        public AddOrderRegelToOrderRequest() {
        }
        
        public AddOrderRegelToOrderRequest(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrder AddOrderRegelToOrder) {
            this.AddOrderRegelToOrder = AddOrderRegelToOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderRegelToOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrderRegelToOrderResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderRegel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponseOrderRegel[] AddOrderRegelToOrderResponse1;
        
        public AddOrderRegelToOrderResponse() {
        }
        
        public AddOrderRegelToOrderResponse(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponseOrderRegel[] AddOrderRegelToOrderResponse1) {
            this.AddOrderRegelToOrderResponse1 = AddOrderRegelToOrderResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderManagementPortTypeChannel : Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderManagementPortTypeClient : System.ServiceModel.ClientBase<Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType>, Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType {
        
        public OrderManagementPortTypeClient() {
        }
        
        public OrderManagementPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderManagementPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagementPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagementPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponse Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.GetOrderVoorGebuiker(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest request) {
            return base.Channel.GetOrderVoorGebuiker(request);
        }
        
        public Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponseOrder[] GetOrderVoorGebuiker(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker1) {
            Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest inValue = new Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest();
            inValue.GetOrderVoorGebuiker = GetOrderVoorGebuiker1;
            Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponse retVal = ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).GetOrderVoorGebuiker(inValue);
            return retVal.GetOrderVoorGebuikerResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponse> Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.GetOrderVoorGebuikerAsync(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest request) {
            return base.Channel.GetOrderVoorGebuikerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerResponse> GetOrderVoorGebuikerAsync(Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker) {
            Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest inValue = new Mvc3LetsShopProject.MendixOrderService.GetOrderVoorGebuikerRequest();
            inValue.GetOrderVoorGebuiker = GetOrderVoorGebuiker;
            return ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).GetOrderVoorGebuikerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponse Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.GetOrderRegels(Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest request) {
            return base.Channel.GetOrderRegels(request);
        }
        
        public Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponseOrderRegel[] GetOrderRegels(Mvc3LetsShopProject.MendixOrderService.GetOrderRegels GetOrderRegels1) {
            Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest inValue = new Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest();
            inValue.GetOrderRegels = GetOrderRegels1;
            Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponse retVal = ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).GetOrderRegels(inValue);
            return retVal.GetOrderRegelsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponse> Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.GetOrderRegelsAsync(Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest request) {
            return base.Channel.GetOrderRegelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsResponse> GetOrderRegelsAsync(Mvc3LetsShopProject.MendixOrderService.GetOrderRegels GetOrderRegels) {
            Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest inValue = new Mvc3LetsShopProject.MendixOrderService.GetOrderRegelsRequest();
            inValue.GetOrderRegels = GetOrderRegels;
            return ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).GetOrderRegelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse1 Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.AddOrderForGebruiker(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest request) {
            return base.Channel.AddOrderForGebruiker(request);
        }
        
        public Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse AddOrderForGebruiker(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruiker AddOrderForGebruiker1) {
            Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest inValue = new Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest();
            inValue.AddOrderForGebruiker = AddOrderForGebruiker1;
            Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse1 retVal = ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).AddOrderForGebruiker(inValue);
            return retVal.AddOrderForGebruikerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse1> Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.AddOrderForGebruikerAsync(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest request) {
            return base.Channel.AddOrderForGebruikerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerResponse1> AddOrderForGebruikerAsync(Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruiker AddOrderForGebruiker) {
            Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest inValue = new Mvc3LetsShopProject.MendixOrderService.AddOrderForGebruikerRequest();
            inValue.AddOrderForGebruiker = AddOrderForGebruiker;
            return ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).AddOrderForGebruikerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponse Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.AddOrderRegelToOrder(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest request) {
            return base.Channel.AddOrderRegelToOrder(request);
        }
        
        public Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponseOrderRegel[] AddOrderRegelToOrder(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrder AddOrderRegelToOrder1) {
            Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest inValue = new Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest();
            inValue.AddOrderRegelToOrder = AddOrderRegelToOrder1;
            Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponse retVal = ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).AddOrderRegelToOrder(inValue);
            return retVal.AddOrderRegelToOrderResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponse> Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType.AddOrderRegelToOrderAsync(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest request) {
            return base.Channel.AddOrderRegelToOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderResponse> AddOrderRegelToOrderAsync(Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrder AddOrderRegelToOrder) {
            Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest inValue = new Mvc3LetsShopProject.MendixOrderService.AddOrderRegelToOrderRequest();
            inValue.AddOrderRegelToOrder = AddOrderRegelToOrder;
            return ((Mvc3LetsShopProject.MendixOrderService.OrderManagementPortType)(this)).AddOrderRegelToOrderAsync(inValue);
        }
    }
}
