//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassLibrary.MendixOrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.com/", ConfigurationName="MendixOrderService.OrderManagementPortType")]
    public interface OrderManagementPortType {
        
        // CODEGEN: Generating message contract since the operation GetOrderVoorGebuiker is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderVoorGebuiker", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponse GetOrderVoorGebuiker(DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderVoorGebuiker", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponse> GetOrderVoorGebuikerAsync(DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest request);
        
        // CODEGEN: Generating message contract since the operation GetOrderRegels is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderRegels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixOrderService.GetOrderRegelsResponse GetOrderRegels(DataClassLibrary.MendixOrderService.GetOrderRegelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetOrderRegels", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixOrderService.GetOrderRegelsResponse> GetOrderRegelsAsync(DataClassLibrary.MendixOrderService.GetOrderRegelsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderVoorGebuiker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long gebruikerIdField;
        
        private GetOrderVoorGebuikerOrderStatus orderStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GetOrderVoorGebuikerOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum GetOrderVoorGebuikerOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderVoorGebuikerResponseOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderNummerField;
        
        private System.DateTime orderDatumField;
        
        private GetOrderVoorGebuikerResponseOrderOrderStatus orderStatusField;
        
        private long gebruikerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OrderNummer {
            get {
                return this.orderNummerField;
            }
            set {
                this.orderNummerField = value;
                this.RaisePropertyChanged("OrderNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime OrderDatum {
            get {
                return this.orderDatumField;
            }
            set {
                this.orderDatumField = value;
                this.RaisePropertyChanged("OrderDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public GetOrderVoorGebuikerResponseOrderOrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum GetOrderVoorGebuikerResponseOrderOrderStatus {
        
        /// <remarks/>
        InWinkelwagen,
        
        /// <remarks/>
        Besteld,
        
        /// <remarks/>
        Verstuurd,
        
        /// <remarks/>
        Ontvangen,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderVoorGebuikerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker;
        
        public GetOrderVoorGebuikerRequest() {
        }
        
        public GetOrderVoorGebuikerRequest(DataClassLibrary.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker) {
            this.GetOrderVoorGebuiker = GetOrderVoorGebuiker;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderVoorGebuikerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderVoorGebuikerResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Order", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponseOrder[] GetOrderVoorGebuikerResponse1;
        
        public GetOrderVoorGebuikerResponse() {
        }
        
        public GetOrderVoorGebuikerResponse(DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponseOrder[] GetOrderVoorGebuikerResponse1) {
            this.GetOrderVoorGebuikerResponse1 = GetOrderVoorGebuikerResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderRegels : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderNummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OrderNummer {
            get {
                return this.orderNummerField;
            }
            set {
                this.orderNummerField = value;
                this.RaisePropertyChanged("OrderNummer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetOrderRegelsResponseOrderRegel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelIdField;
        
        private long leverancierIdField;
        
        private decimal verkoopprijsField;
        
        private long aantalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ArtikelId {
            get {
                return this.artikelIdField;
            }
            set {
                this.artikelIdField = value;
                this.RaisePropertyChanged("ArtikelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LeverancierId {
            get {
                return this.leverancierIdField;
            }
            set {
                this.leverancierIdField = value;
                this.RaisePropertyChanged("LeverancierId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long Aantal {
            get {
                return this.aantalField;
            }
            set {
                this.aantalField = value;
                this.RaisePropertyChanged("Aantal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderRegelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixOrderService.GetOrderRegels GetOrderRegels;
        
        public GetOrderRegelsRequest() {
        }
        
        public GetOrderRegelsRequest(DataClassLibrary.MendixOrderService.GetOrderRegels GetOrderRegels) {
            this.GetOrderRegels = GetOrderRegels;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderRegelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderRegelsResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderRegel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataClassLibrary.MendixOrderService.GetOrderRegelsResponseOrderRegel[] GetOrderRegelsResponse1;
        
        public GetOrderRegelsResponse() {
        }
        
        public GetOrderRegelsResponse(DataClassLibrary.MendixOrderService.GetOrderRegelsResponseOrderRegel[] GetOrderRegelsResponse1) {
            this.GetOrderRegelsResponse1 = GetOrderRegelsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderManagementPortTypeChannel : DataClassLibrary.MendixOrderService.OrderManagementPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderManagementPortTypeClient : System.ServiceModel.ClientBase<DataClassLibrary.MendixOrderService.OrderManagementPortType>, DataClassLibrary.MendixOrderService.OrderManagementPortType {
        
        public OrderManagementPortTypeClient() {
        }
        
        public OrderManagementPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderManagementPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagementPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagementPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponse DataClassLibrary.MendixOrderService.OrderManagementPortType.GetOrderVoorGebuiker(DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest request) {
            return base.Channel.GetOrderVoorGebuiker(request);
        }
        
        public DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponseOrder[] GetOrderVoorGebuiker(DataClassLibrary.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker1) {
            DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest inValue = new DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest();
            inValue.GetOrderVoorGebuiker = GetOrderVoorGebuiker1;
            DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponse retVal = ((DataClassLibrary.MendixOrderService.OrderManagementPortType)(this)).GetOrderVoorGebuiker(inValue);
            return retVal.GetOrderVoorGebuikerResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponse> DataClassLibrary.MendixOrderService.OrderManagementPortType.GetOrderVoorGebuikerAsync(DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest request) {
            return base.Channel.GetOrderVoorGebuikerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerResponse> GetOrderVoorGebuikerAsync(DataClassLibrary.MendixOrderService.GetOrderVoorGebuiker GetOrderVoorGebuiker) {
            DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest inValue = new DataClassLibrary.MendixOrderService.GetOrderVoorGebuikerRequest();
            inValue.GetOrderVoorGebuiker = GetOrderVoorGebuiker;
            return ((DataClassLibrary.MendixOrderService.OrderManagementPortType)(this)).GetOrderVoorGebuikerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixOrderService.GetOrderRegelsResponse DataClassLibrary.MendixOrderService.OrderManagementPortType.GetOrderRegels(DataClassLibrary.MendixOrderService.GetOrderRegelsRequest request) {
            return base.Channel.GetOrderRegels(request);
        }
        
        public DataClassLibrary.MendixOrderService.GetOrderRegelsResponseOrderRegel[] GetOrderRegels(DataClassLibrary.MendixOrderService.GetOrderRegels GetOrderRegels1) {
            DataClassLibrary.MendixOrderService.GetOrderRegelsRequest inValue = new DataClassLibrary.MendixOrderService.GetOrderRegelsRequest();
            inValue.GetOrderRegels = GetOrderRegels1;
            DataClassLibrary.MendixOrderService.GetOrderRegelsResponse retVal = ((DataClassLibrary.MendixOrderService.OrderManagementPortType)(this)).GetOrderRegels(inValue);
            return retVal.GetOrderRegelsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixOrderService.GetOrderRegelsResponse> DataClassLibrary.MendixOrderService.OrderManagementPortType.GetOrderRegelsAsync(DataClassLibrary.MendixOrderService.GetOrderRegelsRequest request) {
            return base.Channel.GetOrderRegelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixOrderService.GetOrderRegelsResponse> GetOrderRegelsAsync(DataClassLibrary.MendixOrderService.GetOrderRegels GetOrderRegels) {
            DataClassLibrary.MendixOrderService.GetOrderRegelsRequest inValue = new DataClassLibrary.MendixOrderService.GetOrderRegelsRequest();
            inValue.GetOrderRegels = GetOrderRegels;
            return ((DataClassLibrary.MendixOrderService.OrderManagementPortType)(this)).GetOrderRegelsAsync(inValue);
        }
    }
}
