//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassLibrary.MendixGebruikersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.com/", ConfigurationName="MendixGebruikersService.GebruikersServicePortType")]
    public interface GebruikersServicePortType {
        
        // CODEGEN: Generating message contract since the operation GetGebruiker is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetGebruiker", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixGebruikersService.GetGebruikerResponse1 GetGebruiker(DataClassLibrary.MendixGebruikersService.GetGebruikerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetGebruiker", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixGebruikersService.GetGebruikerResponse1> GetGebruikerAsync(DataClassLibrary.MendixGebruikersService.GetGebruikerRequest request);
        
        // CODEGEN: Generating message contract since the operation GetGebruikers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetGebruikers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixGebruikersService.GetGebruikersResponse GetGebruikers(DataClassLibrary.MendixGebruikersService.GetGebruikersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/GetGebruikers", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixGebruikersService.GetGebruikersResponse> GetGebruikersAsync(DataClassLibrary.MendixGebruikersService.GetGebruikersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruiker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamField;
        
        private string wachtwoordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Wachtwoord {
            get {
                return this.wachtwoordField;
            }
            set {
                this.wachtwoordField = value;
                this.RaisePropertyChanged("Wachtwoord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetGebruikerResponseResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetGebruikerResponseResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikerResponseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string voornaamField;
        
        private string achternaamField;
        
        private string straatField;
        
        private string huisnummerField;
        
        private string postcodeField;
        
        private string plaatsField;
        
        private string landField;
        
        private System.Nullable<long> telefoonnummerPriveField;
        
        private System.Nullable<long> telefoonnummerZakelijkInternField;
        
        private System.Nullable<long> telefoonnummerZakelijkExternField;
        
        private string emailadresField;
        
        private string naamField;
        
        private string fullNameField;
        
        private string emailField;
        
        private bool isLocalUserField;
        
        private string nameField;
        
        private string passwordField;
        
        private System.Nullable<System.DateTime> lastLoginField;
        
        private bool blockedField;
        
        private bool activeField;
        
        private System.Nullable<long> failedLoginsField;
        
        private bool webServiceUserField;
        
        private bool isAnonymousField;
        
        private long gebruikerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Voornaam {
            get {
                return this.voornaamField;
            }
            set {
                this.voornaamField = value;
                this.RaisePropertyChanged("Voornaam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Achternaam {
            get {
                return this.achternaamField;
            }
            set {
                this.achternaamField = value;
                this.RaisePropertyChanged("Achternaam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Straat {
            get {
                return this.straatField;
            }
            set {
                this.straatField = value;
                this.RaisePropertyChanged("Straat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Huisnummer {
            get {
                return this.huisnummerField;
            }
            set {
                this.huisnummerField = value;
                this.RaisePropertyChanged("Huisnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string Plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
                this.RaisePropertyChanged("Plaats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string Land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
                this.RaisePropertyChanged("Land");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<long> TelefoonnummerPrive {
            get {
                return this.telefoonnummerPriveField;
            }
            set {
                this.telefoonnummerPriveField = value;
                this.RaisePropertyChanged("TelefoonnummerPrive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<long> TelefoonnummerZakelijkIntern {
            get {
                return this.telefoonnummerZakelijkInternField;
            }
            set {
                this.telefoonnummerZakelijkInternField = value;
                this.RaisePropertyChanged("TelefoonnummerZakelijkIntern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<long> TelefoonnummerZakelijkExtern {
            get {
                return this.telefoonnummerZakelijkExternField;
            }
            set {
                this.telefoonnummerZakelijkExternField = value;
                this.RaisePropertyChanged("TelefoonnummerZakelijkExtern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string Emailadres {
            get {
                return this.emailadresField;
            }
            set {
                this.emailadresField = value;
                this.RaisePropertyChanged("Emailadres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool IsLocalUser {
            get {
                return this.isLocalUserField;
            }
            set {
                this.isLocalUserField = value;
                this.RaisePropertyChanged("IsLocalUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> LastLogin {
            get {
                return this.lastLoginField;
            }
            set {
                this.lastLoginField = value;
                this.RaisePropertyChanged("LastLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public System.Nullable<long> FailedLogins {
            get {
                return this.failedLoginsField;
            }
            set {
                this.failedLoginsField = value;
                this.RaisePropertyChanged("FailedLogins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public bool WebServiceUser {
            get {
                return this.webServiceUserField;
            }
            set {
                this.webServiceUserField = value;
                this.RaisePropertyChanged("WebServiceUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public bool IsAnonymous {
            get {
                return this.isAnonymousField;
            }
            set {
                this.isAnonymousField = value;
                this.RaisePropertyChanged("IsAnonymous");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGebruikerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixGebruikersService.GetGebruiker GetGebruiker;
        
        public GetGebruikerRequest() {
        }
        
        public GetGebruikerRequest(DataClassLibrary.MendixGebruikersService.GetGebruiker GetGebruiker) {
            this.GetGebruiker = GetGebruiker;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGebruikerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixGebruikersService.GetGebruikerResponse GetGebruikerResponse;
        
        public GetGebruikerResponse1() {
        }
        
        public GetGebruikerResponse1(DataClassLibrary.MendixGebruikersService.GetGebruikerResponse GetGebruikerResponse) {
            this.GetGebruikerResponse = GetGebruikerResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikers : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikersResponseGebruiker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long gebruikerIdField;
        
        private string voornaamField;
        
        private string achternaamField;
        
        private string straatField;
        
        private string huisnummerField;
        
        private string postcodeField;
        
        private string plaatsField;
        
        private string emailadresField;
        
        private string naamField;
        
        private string emailField;
        
        private string nameField;
        
        private GetGebruikersResponseGebruikerGebruiker_Functie gebruiker_FunctieField;
        
        private GetGebruikersResponseGebruikerGebruiker_Afdeling gebruiker_AfdelingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long GebruikerId {
            get {
                return this.gebruikerIdField;
            }
            set {
                this.gebruikerIdField = value;
                this.RaisePropertyChanged("GebruikerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Voornaam {
            get {
                return this.voornaamField;
            }
            set {
                this.voornaamField = value;
                this.RaisePropertyChanged("Voornaam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Achternaam {
            get {
                return this.achternaamField;
            }
            set {
                this.achternaamField = value;
                this.RaisePropertyChanged("Achternaam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Straat {
            get {
                return this.straatField;
            }
            set {
                this.straatField = value;
                this.RaisePropertyChanged("Straat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Huisnummer {
            get {
                return this.huisnummerField;
            }
            set {
                this.huisnummerField = value;
                this.RaisePropertyChanged("Huisnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
                this.RaisePropertyChanged("Plaats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string Emailadres {
            get {
                return this.emailadresField;
            }
            set {
                this.emailadresField = value;
                this.RaisePropertyChanged("Emailadres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public GetGebruikersResponseGebruikerGebruiker_Functie Gebruiker_Functie {
            get {
                return this.gebruiker_FunctieField;
            }
            set {
                this.gebruiker_FunctieField = value;
                this.RaisePropertyChanged("Gebruiker_Functie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public GetGebruikersResponseGebruikerGebruiker_Afdeling Gebruiker_Afdeling {
            get {
                return this.gebruiker_AfdelingField;
            }
            set {
                this.gebruiker_AfdelingField = value;
                this.RaisePropertyChanged("Gebruiker_Afdeling");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikersResponseGebruikerGebruiker_Functie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetGebruikersResponseGebruikerGebruiker_FunctieFunctie functieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetGebruikersResponseGebruikerGebruiker_FunctieFunctie Functie {
            get {
                return this.functieField;
            }
            set {
                this.functieField = value;
                this.RaisePropertyChanged("Functie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikersResponseGebruikerGebruiker_FunctieFunctie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamField;
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikersResponseGebruikerGebruiker_Afdeling : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetGebruikersResponseGebruikerGebruiker_AfdelingAfdeling afdelingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetGebruikersResponseGebruikerGebruiker_AfdelingAfdeling Afdeling {
            get {
                return this.afdelingField;
            }
            set {
                this.afdelingField = value;
                this.RaisePropertyChanged("Afdeling");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class GetGebruikersResponseGebruikerGebruiker_AfdelingAfdeling : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamField;
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGebruikersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixGebruikersService.GetGebruikers GetGebruikers;
        
        public GetGebruikersRequest() {
        }
        
        public GetGebruikersRequest(DataClassLibrary.MendixGebruikersService.GetGebruikers GetGebruikers) {
            this.GetGebruikers = GetGebruikers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGebruikersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGebruikersResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Gebruiker", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataClassLibrary.MendixGebruikersService.GetGebruikersResponseGebruiker[] GetGebruikersResponse1;
        
        public GetGebruikersResponse() {
        }
        
        public GetGebruikersResponse(DataClassLibrary.MendixGebruikersService.GetGebruikersResponseGebruiker[] GetGebruikersResponse1) {
            this.GetGebruikersResponse1 = GetGebruikersResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GebruikersServicePortTypeChannel : DataClassLibrary.MendixGebruikersService.GebruikersServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GebruikersServicePortTypeClient : System.ServiceModel.ClientBase<DataClassLibrary.MendixGebruikersService.GebruikersServicePortType>, DataClassLibrary.MendixGebruikersService.GebruikersServicePortType {
        
        public GebruikersServicePortTypeClient() {
        }
        
        public GebruikersServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GebruikersServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GebruikersServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GebruikersServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixGebruikersService.GetGebruikerResponse1 DataClassLibrary.MendixGebruikersService.GebruikersServicePortType.GetGebruiker(DataClassLibrary.MendixGebruikersService.GetGebruikerRequest request) {
            return base.Channel.GetGebruiker(request);
        }
        
        public DataClassLibrary.MendixGebruikersService.GetGebruikerResponse GetGebruiker(DataClassLibrary.MendixGebruikersService.GetGebruiker GetGebruiker1) {
            DataClassLibrary.MendixGebruikersService.GetGebruikerRequest inValue = new DataClassLibrary.MendixGebruikersService.GetGebruikerRequest();
            inValue.GetGebruiker = GetGebruiker1;
            DataClassLibrary.MendixGebruikersService.GetGebruikerResponse1 retVal = ((DataClassLibrary.MendixGebruikersService.GebruikersServicePortType)(this)).GetGebruiker(inValue);
            return retVal.GetGebruikerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixGebruikersService.GetGebruikerResponse1> DataClassLibrary.MendixGebruikersService.GebruikersServicePortType.GetGebruikerAsync(DataClassLibrary.MendixGebruikersService.GetGebruikerRequest request) {
            return base.Channel.GetGebruikerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixGebruikersService.GetGebruikerResponse1> GetGebruikerAsync(DataClassLibrary.MendixGebruikersService.GetGebruiker GetGebruiker) {
            DataClassLibrary.MendixGebruikersService.GetGebruikerRequest inValue = new DataClassLibrary.MendixGebruikersService.GetGebruikerRequest();
            inValue.GetGebruiker = GetGebruiker;
            return ((DataClassLibrary.MendixGebruikersService.GebruikersServicePortType)(this)).GetGebruikerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixGebruikersService.GetGebruikersResponse DataClassLibrary.MendixGebruikersService.GebruikersServicePortType.GetGebruikers(DataClassLibrary.MendixGebruikersService.GetGebruikersRequest request) {
            return base.Channel.GetGebruikers(request);
        }
        
        public DataClassLibrary.MendixGebruikersService.GetGebruikersResponseGebruiker[] GetGebruikers(DataClassLibrary.MendixGebruikersService.GetGebruikers GetGebruikers1) {
            DataClassLibrary.MendixGebruikersService.GetGebruikersRequest inValue = new DataClassLibrary.MendixGebruikersService.GetGebruikersRequest();
            inValue.GetGebruikers = GetGebruikers1;
            DataClassLibrary.MendixGebruikersService.GetGebruikersResponse retVal = ((DataClassLibrary.MendixGebruikersService.GebruikersServicePortType)(this)).GetGebruikers(inValue);
            return retVal.GetGebruikersResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixGebruikersService.GetGebruikersResponse> DataClassLibrary.MendixGebruikersService.GebruikersServicePortType.GetGebruikersAsync(DataClassLibrary.MendixGebruikersService.GetGebruikersRequest request) {
            return base.Channel.GetGebruikersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixGebruikersService.GetGebruikersResponse> GetGebruikersAsync(DataClassLibrary.MendixGebruikersService.GetGebruikers GetGebruikers) {
            DataClassLibrary.MendixGebruikersService.GetGebruikersRequest inValue = new DataClassLibrary.MendixGebruikersService.GetGebruikersRequest();
            inValue.GetGebruikers = GetGebruikers;
            return ((DataClassLibrary.MendixGebruikersService.GebruikersServicePortType)(this)).GetGebruikersAsync(inValue);
        }
    }
}
