//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassLibrary.MendixArtikelenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.com/", ConfigurationName="MendixArtikelenService.ArtikelenServicePortType")]
    public interface ArtikelenServicePortType {
        
        // CODEGEN: Generating message contract since the operation mfGetArtikelen is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfGetArtikelen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponse mfGetArtikelen(DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfGetArtikelen", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponse> mfGetArtikelenAsync(DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest request);
        
        // CODEGEN: Generating message contract since the operation mfAddArtikel is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfAddArtikel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse1 mfAddArtikel(DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfAddArtikel", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse1> mfAddArtikelAsync(DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest request);
        
        // CODEGEN: Generating message contract since the operation mfGetCategorieen is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfGetCategorieen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponse mfGetCategorieen(DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfGetCategorieen", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponse> mfGetCategorieenAsync(DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest request);
        
        // CODEGEN: Generating message contract since the operation mfGetArtikelMetArtikelcode is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfGetArtikelMetArtikelcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse1 mfGetArtikelMetArtikelcode(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/mfGetArtikelMetArtikelcode", ReplyAction="*")]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse1> mfGetArtikelMetArtikelcodeAsync(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long pageSizeField;
        
        private long offSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long OffSet {
            get {
                return this.offSetField;
            }
            set {
                this.offSetField = value;
                this.RaisePropertyChanged("OffSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelenResponseArtikel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> artikelcodeField;
        
        private string omschrijvingField;
        
        private System.Nullable<decimal> verkoopprijsField;
        
        private System.Nullable<decimal> inkoopprijsField;
        
        private System.Nullable<System.DateTime> startdatumField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private System.Nullable<mfGetArtikelenResponseArtikelStatus> statusField;
        
        private System.Nullable<long> voorraadField;
        
        private string artikelcode_OmschrijvingField;
        
        private mfGetArtikelenResponseArtikelArtikel_Categorie artikel_CategorieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> Artikelcode {
            get {
                return this.artikelcodeField;
            }
            set {
                this.artikelcodeField = value;
                this.RaisePropertyChanged("Artikelcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<decimal> Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<decimal> Inkoopprijs {
            get {
                return this.inkoopprijsField;
            }
            set {
                this.inkoopprijsField = value;
                this.RaisePropertyChanged("Inkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> Startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
                this.RaisePropertyChanged("Startdatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> Einddatum {
            get {
                return this.einddatumField;
            }
            set {
                this.einddatumField = value;
                this.RaisePropertyChanged("Einddatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<mfGetArtikelenResponseArtikelStatus> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<long> Voorraad {
            get {
                return this.voorraadField;
            }
            set {
                this.voorraadField = value;
                this.RaisePropertyChanged("Voorraad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string Artikelcode_Omschrijving {
            get {
                return this.artikelcode_OmschrijvingField;
            }
            set {
                this.artikelcode_OmschrijvingField = value;
                this.RaisePropertyChanged("Artikelcode_Omschrijving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public mfGetArtikelenResponseArtikelArtikel_Categorie Artikel_Categorie {
            get {
                return this.artikel_CategorieField;
            }
            set {
                this.artikel_CategorieField = value;
                this.RaisePropertyChanged("Artikel_Categorie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum mfGetArtikelenResponseArtikelStatus {
        
        /// <remarks/>
        Actief,
        
        /// <remarks/>
        Inactief,
        
        /// <remarks/>
        Geblokkeerd,
        
        /// <remarks/>
        Vervallen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelenResponseArtikelArtikel_Categorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mfGetArtikelenResponseArtikelArtikel_CategorieCategorie categorieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mfGetArtikelenResponseArtikelArtikel_CategorieCategorie Categorie {
            get {
                return this.categorieField;
            }
            set {
                this.categorieField = value;
                this.RaisePropertyChanged("Categorie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelenResponseArtikelArtikel_CategorieCategorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfGetArtikelenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixArtikelenService.mfGetArtikelen mfGetArtikelen;
        
        public mfGetArtikelenRequest() {
        }
        
        public mfGetArtikelenRequest(DataClassLibrary.MendixArtikelenService.mfGetArtikelen mfGetArtikelen) {
            this.mfGetArtikelen = mfGetArtikelen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfGetArtikelenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mfGetArtikelenResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Artikel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponseArtikel[] mfGetArtikelenResponse1;
        
        public mfGetArtikelenResponse() {
        }
        
        public mfGetArtikelenResponse(DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponseArtikel[] mfGetArtikelenResponse1) {
            this.mfGetArtikelenResponse1 = mfGetArtikelenResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfAddArtikel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mfAddArtikelArtikel artikelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mfAddArtikelArtikel Artikel {
            get {
                return this.artikelField;
            }
            set {
                this.artikelField = value;
                this.RaisePropertyChanged("Artikel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfAddArtikelArtikel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string omschrijvingField;
        
        private decimal verkoopprijsField;
        
        private decimal inkoopprijsField;
        
        private System.DateTime startdatumField;
        
        private System.DateTime einddatumField;
        
        private mfAddArtikelArtikelStatus statusField;
        
        private long voorraadField;
        
        private string artikelcode_OmschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Inkoopprijs {
            get {
                return this.inkoopprijsField;
            }
            set {
                this.inkoopprijsField = value;
                this.RaisePropertyChanged("Inkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime Startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
                this.RaisePropertyChanged("Startdatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime Einddatum {
            get {
                return this.einddatumField;
            }
            set {
                this.einddatumField = value;
                this.RaisePropertyChanged("Einddatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public mfAddArtikelArtikelStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long Voorraad {
            get {
                return this.voorraadField;
            }
            set {
                this.voorraadField = value;
                this.RaisePropertyChanged("Voorraad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Artikelcode_Omschrijving {
            get {
                return this.artikelcode_OmschrijvingField;
            }
            set {
                this.artikelcode_OmschrijvingField = value;
                this.RaisePropertyChanged("Artikelcode_Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum mfAddArtikelArtikelStatus {
        
        /// <remarks/>
        Actief,
        
        /// <remarks/>
        Inactief,
        
        /// <remarks/>
        Geblokkeerd,
        
        /// <remarks/>
        Vervallen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfAddArtikelResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfAddArtikelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixArtikelenService.mfAddArtikel mfAddArtikel;
        
        public mfAddArtikelRequest() {
        }
        
        public mfAddArtikelRequest(DataClassLibrary.MendixArtikelenService.mfAddArtikel mfAddArtikel) {
            this.mfAddArtikel = mfAddArtikel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfAddArtikelResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse mfAddArtikelResponse;
        
        public mfAddArtikelResponse1() {
        }
        
        public mfAddArtikelResponse1(DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse mfAddArtikelResponse) {
            this.mfAddArtikelResponse = mfAddArtikelResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetCategorieen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long pageSizeField;
        
        private long offSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long OffSet {
            get {
                return this.offSetField;
            }
            set {
                this.offSetField = value;
                this.RaisePropertyChanged("OffSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetCategorieenResponseCategorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfGetCategorieenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixArtikelenService.mfGetCategorieen mfGetCategorieen;
        
        public mfGetCategorieenRequest() {
        }
        
        public mfGetCategorieenRequest(DataClassLibrary.MendixArtikelenService.mfGetCategorieen mfGetCategorieen) {
            this.mfGetCategorieen = mfGetCategorieen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfGetCategorieenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mfGetCategorieenResponse", Namespace="http://www.example.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Categorie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponseCategorie[] mfGetCategorieenResponse1;
        
        public mfGetCategorieenResponse() {
        }
        
        public mfGetCategorieenResponse(DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponseCategorie[] mfGetCategorieenResponse1) {
            this.mfGetCategorieenResponse1 = mfGetCategorieenResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ArtikelCode {
            get {
                return this.artikelCodeField;
            }
            set {
                this.artikelCodeField = value;
                this.RaisePropertyChanged("ArtikelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mfGetArtikelMetArtikelcodeResponseArtikel artikelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mfGetArtikelMetArtikelcodeResponseArtikel Artikel {
            get {
                return this.artikelField;
            }
            set {
                this.artikelField = value;
                this.RaisePropertyChanged("Artikel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long artikelcodeField;
        
        private string omschrijvingField;
        
        private decimal verkoopprijsField;
        
        private System.Nullable<decimal> inkoopprijsField;
        
        private System.Nullable<System.DateTime> startdatumField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private System.Nullable<mfGetArtikelMetArtikelcodeResponseArtikelStatus> statusField;
        
        private System.Nullable<long> voorraadField;
        
        private string artikelcode_OmschrijvingField;
        
        private mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Eenheid artikel_EenheidField;
        
        private mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Afbeelding artikel_AfbeeldingField;
        
        private mfGetArtikelMetArtikelcodeResponseArtikelVoorraad[] voorraad_ArtikelField;
        
        private mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Categorie artikel_CategorieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Artikelcode {
            get {
                return this.artikelcodeField;
            }
            set {
                this.artikelcodeField = value;
                this.RaisePropertyChanged("Artikelcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Verkoopprijs {
            get {
                return this.verkoopprijsField;
            }
            set {
                this.verkoopprijsField = value;
                this.RaisePropertyChanged("Verkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<decimal> Inkoopprijs {
            get {
                return this.inkoopprijsField;
            }
            set {
                this.inkoopprijsField = value;
                this.RaisePropertyChanged("Inkoopprijs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> Startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
                this.RaisePropertyChanged("Startdatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> Einddatum {
            get {
                return this.einddatumField;
            }
            set {
                this.einddatumField = value;
                this.RaisePropertyChanged("Einddatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<mfGetArtikelMetArtikelcodeResponseArtikelStatus> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<long> Voorraad {
            get {
                return this.voorraadField;
            }
            set {
                this.voorraadField = value;
                this.RaisePropertyChanged("Voorraad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string Artikelcode_Omschrijving {
            get {
                return this.artikelcode_OmschrijvingField;
            }
            set {
                this.artikelcode_OmschrijvingField = value;
                this.RaisePropertyChanged("Artikelcode_Omschrijving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Eenheid Artikel_Eenheid {
            get {
                return this.artikel_EenheidField;
            }
            set {
                this.artikel_EenheidField = value;
                this.RaisePropertyChanged("Artikel_Eenheid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Afbeelding Artikel_Afbeelding {
            get {
                return this.artikel_AfbeeldingField;
            }
            set {
                this.artikel_AfbeeldingField = value;
                this.RaisePropertyChanged("Artikel_Afbeelding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Voorraad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public mfGetArtikelMetArtikelcodeResponseArtikelVoorraad[] Voorraad_Artikel {
            get {
                return this.voorraad_ArtikelField;
            }
            set {
                this.voorraad_ArtikelField = value;
                this.RaisePropertyChanged("Voorraad_Artikel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Categorie Artikel_Categorie {
            get {
                return this.artikel_CategorieField;
            }
            set {
                this.artikel_CategorieField = value;
                this.RaisePropertyChanged("Artikel_Categorie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public enum mfGetArtikelMetArtikelcodeResponseArtikelStatus {
        
        /// <remarks/>
        Actief,
        
        /// <remarks/>
        Inactief,
        
        /// <remarks/>
        Geblokkeerd,
        
        /// <remarks/>
        Vervallen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Eenheid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mfGetArtikelMetArtikelcodeResponseArtikelArtikel_EenheidEenheid eenheidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mfGetArtikelMetArtikelcodeResponseArtikelArtikel_EenheidEenheid Eenheid {
            get {
                return this.eenheidField;
            }
            set {
                this.eenheidField = value;
                this.RaisePropertyChanged("Eenheid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelArtikel_EenheidEenheid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Afbeelding : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mfGetArtikelMetArtikelcodeResponseArtikelArtikel_AfbeeldingAfbeelding afbeeldingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mfGetArtikelMetArtikelcodeResponseArtikelArtikel_AfbeeldingAfbeelding Afbeelding {
            get {
                return this.afbeeldingField;
            }
            set {
                this.afbeeldingField = value;
                this.RaisePropertyChanged("Afbeelding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelArtikel_AfbeeldingAfbeelding : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> fileIDField;
        
        private byte[] contentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> FileID {
            get {
                return this.fileIDField;
            }
            set {
                this.fileIDField = value;
                this.RaisePropertyChanged("FileID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=1)]
        public byte[] Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
                this.RaisePropertyChanged("Contents");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelVoorraad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> aantalField;
        
        private System.Nullable<System.DateTime> datumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> Aantal {
            get {
                return this.aantalField;
            }
            set {
                this.aantalField = value;
                this.RaisePropertyChanged("Aantal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("Datum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelArtikel_Categorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mfGetArtikelMetArtikelcodeResponseArtikelArtikel_CategorieCategorie categorieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mfGetArtikelMetArtikelcodeResponseArtikelArtikel_CategorieCategorie Categorie {
            get {
                return this.categorieField;
            }
            set {
                this.categorieField = value;
                this.RaisePropertyChanged("Categorie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/")]
    public partial class mfGetArtikelMetArtikelcodeResponseArtikelArtikel_CategorieCategorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfGetArtikelMetArtikelcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcode mfGetArtikelMetArtikelcode;
        
        public mfGetArtikelMetArtikelcodeRequest() {
        }
        
        public mfGetArtikelMetArtikelcodeRequest(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcode mfGetArtikelMetArtikelcode) {
            this.mfGetArtikelMetArtikelcode = mfGetArtikelMetArtikelcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mfGetArtikelMetArtikelcodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.com/", Order=0)]
        public DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse mfGetArtikelMetArtikelcodeResponse;
        
        public mfGetArtikelMetArtikelcodeResponse1() {
        }
        
        public mfGetArtikelMetArtikelcodeResponse1(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse mfGetArtikelMetArtikelcodeResponse) {
            this.mfGetArtikelMetArtikelcodeResponse = mfGetArtikelMetArtikelcodeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArtikelenServicePortTypeChannel : DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtikelenServicePortTypeClient : System.ServiceModel.ClientBase<DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType>, DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType {
        
        public ArtikelenServicePortTypeClient() {
        }
        
        public ArtikelenServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtikelenServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtikelenServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtikelenServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponse DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfGetArtikelen(DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest request) {
            return base.Channel.mfGetArtikelen(request);
        }
        
        public DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponseArtikel[] mfGetArtikelen(DataClassLibrary.MendixArtikelenService.mfGetArtikelen mfGetArtikelen1) {
            DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest inValue = new DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest();
            inValue.mfGetArtikelen = mfGetArtikelen1;
            DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponse retVal = ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfGetArtikelen(inValue);
            return retVal.mfGetArtikelenResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponse> DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfGetArtikelenAsync(DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest request) {
            return base.Channel.mfGetArtikelenAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetArtikelenResponse> mfGetArtikelenAsync(DataClassLibrary.MendixArtikelenService.mfGetArtikelen mfGetArtikelen) {
            DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest inValue = new DataClassLibrary.MendixArtikelenService.mfGetArtikelenRequest();
            inValue.mfGetArtikelen = mfGetArtikelen;
            return ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfGetArtikelenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse1 DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfAddArtikel(DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest request) {
            return base.Channel.mfAddArtikel(request);
        }
        
        public DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse mfAddArtikel(DataClassLibrary.MendixArtikelenService.mfAddArtikel mfAddArtikel1) {
            DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest inValue = new DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest();
            inValue.mfAddArtikel = mfAddArtikel1;
            DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse1 retVal = ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfAddArtikel(inValue);
            return retVal.mfAddArtikelResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse1> DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfAddArtikelAsync(DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest request) {
            return base.Channel.mfAddArtikelAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfAddArtikelResponse1> mfAddArtikelAsync(DataClassLibrary.MendixArtikelenService.mfAddArtikel mfAddArtikel) {
            DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest inValue = new DataClassLibrary.MendixArtikelenService.mfAddArtikelRequest();
            inValue.mfAddArtikel = mfAddArtikel;
            return ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfAddArtikelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponse DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfGetCategorieen(DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest request) {
            return base.Channel.mfGetCategorieen(request);
        }
        
        public DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponseCategorie[] mfGetCategorieen(DataClassLibrary.MendixArtikelenService.mfGetCategorieen mfGetCategorieen1) {
            DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest inValue = new DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest();
            inValue.mfGetCategorieen = mfGetCategorieen1;
            DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponse retVal = ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfGetCategorieen(inValue);
            return retVal.mfGetCategorieenResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponse> DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfGetCategorieenAsync(DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest request) {
            return base.Channel.mfGetCategorieenAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetCategorieenResponse> mfGetCategorieenAsync(DataClassLibrary.MendixArtikelenService.mfGetCategorieen mfGetCategorieen) {
            DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest inValue = new DataClassLibrary.MendixArtikelenService.mfGetCategorieenRequest();
            inValue.mfGetCategorieen = mfGetCategorieen;
            return ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfGetCategorieenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse1 DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfGetArtikelMetArtikelcode(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest request) {
            return base.Channel.mfGetArtikelMetArtikelcode(request);
        }
        
        public DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse mfGetArtikelMetArtikelcode(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcode mfGetArtikelMetArtikelcode1) {
            DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest inValue = new DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest();
            inValue.mfGetArtikelMetArtikelcode = mfGetArtikelMetArtikelcode1;
            DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse1 retVal = ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfGetArtikelMetArtikelcode(inValue);
            return retVal.mfGetArtikelMetArtikelcodeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse1> DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType.mfGetArtikelMetArtikelcodeAsync(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest request) {
            return base.Channel.mfGetArtikelMetArtikelcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeResponse1> mfGetArtikelMetArtikelcodeAsync(DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcode mfGetArtikelMetArtikelcode) {
            DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest inValue = new DataClassLibrary.MendixArtikelenService.mfGetArtikelMetArtikelcodeRequest();
            inValue.mfGetArtikelMetArtikelcode = mfGetArtikelMetArtikelcode;
            return ((DataClassLibrary.MendixArtikelenService.ArtikelenServicePortType)(this)).mfGetArtikelMetArtikelcodeAsync(inValue);
        }
    }
}
